# Basic Information
title: Ruining Yang
position: Ph.D. Student
affiliation: Stony Brook University
affiliation_link: https://www.stonybrook.edu/
email: ruiniyang (at) cs.stonybrook.edu

# Search Engine Optimization (SEO)
# The following information is used to improve the website traffic from search engines, e.g., Google.
keywords: Ruining Yang, Infrastructure as Code security, supply chain security, credential leakage, honeypot, PragSec Lab, Stony Brook University
description: Ruining Yang is a Ph.D. student at Stony Brook University (PragSec Lab), working on Infrastructure as Code security, supply chain attacks, and credential leakage.
canonical: https://ruiningyang.com/

# Links
# If you don't need one of them, you may delete the corresponding line.
google_scholar: https://scholar.google.com/citations?user=tr75fPMAAAAJ&hl=en
cv_link: assets/files/curriculum_vitae.pdf
github_link: https://github.com/ruiningyang1
linkedin: https://www.linkedin.com/in/ruining-yang-51b90212a/
# twitter: https://twitter.com/              # uncomment and set if you want it

# Images (e.g., your profile picture and your website's favicon)
# "favicon" and "favicon_dark" are used for the light and dark modes, respectively.
avatar: ./assets/img/avatar.png
favicon: ./assets/img/favicon.png
favicon_dark: ./assets/img/favicon-dark.png

# Footnote
# You may use the option to disable the footnote, "Powered by Jekyll and Minimal Light theme."
enable_footnote: true

# Auto Dark Mode
# You may use the option to disable the automatic dark theme
auto_dark_mode: true

# Font
# You can use this option to choose between Serif or Sans Serif fonts.
font: "Serif" # or "Sans Serif"

# Google Analytics ID
# Please remove this if you don't use Google Analytics
# google_analytics: UA-XXXXXXXXX-X

# Use this project as a remote theme for GitHub Pages
# See the guide here: https://docs.github.com/en/pages/setting-up-a-github-pages-site-with-jekyll/adding-a-theme-to-your-github-pages-site-using-jekyll
remote_theme: yaoyao-liu/minimal-light

# The following files will be removed from the generated website.
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - README_zh_Hans.md
  - README_zh_Hant.md
  - README_de.md
  - LICENSE
  - minimal-light.gemspec
  - html_source_file/
